#############################################################################
# Makefile for building: EntornQTGC2
# Generated by qmake (2.01a) (Qt 4.7.4) on: Sun May 27 15:45:56 2012
# Project:  EntornQTGC2.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile EntornQTGC2.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -L/usr/X11R6/lib -lGLEW -lQtOpenGL -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		uigc2.cpp \
		Model.cpp \
		GLWidget.cpp \
		cameracontrol.cpp \
		collisionmanager.cpp \
		coldet/src/box.cpp \
		coldet/src/box_bld.cpp \
		coldet/src/coldet.cpp \
		coldet/src/coldet_bld.cpp \
		coldet/src/math3d.cpp \
		coldet/src/mytritri.cpp \
		coldet/src/sysdep.cpp \
		coldet/src/tritri.c \
		lightmanager.cpp \
		object.cpp \
		objectmanager.cpp \
		lights.cpp \
		expat/xmltok.c \
		expat/xmlrole.c \
		expat/xmlparse.c \
		expat/XMLParser.cpp \
		xmlmanager.cpp \
		glwidgetmap.cpp \
		pointer.cpp \
		glm/glmimg_sim.c \
		glm/glmimg_sdl.c \
		glm/glmimg_png.c \
		glm/glmimg_jpg.c \
		glm/glmimg_devil.c \
		glm/glm.cpp \
		glm/glm_util.cpp \
		glm/glmimg.cpp \
		waymanager.cpp \
		xmlruta.cpp moc_uigc2.cpp \
		moc_GLWidget.cpp \
		qrc_imagenesRutas.cpp
OBJECTS       = main.o \
		uigc2.o \
		Model.o \
		GLWidget.o \
		cameracontrol.o \
		collisionmanager.o \
		box.o \
		box_bld.o \
		coldet.o \
		coldet_bld.o \
		math3d.o \
		mytritri.o \
		sysdep.o \
		tritri.o \
		lightmanager.o \
		object.o \
		objectmanager.o \
		lights.o \
		xmltok.o \
		xmlrole.o \
		xmlparse.o \
		XMLParser.o \
		xmlmanager.o \
		glwidgetmap.o \
		pointer.o \
		glmimg_sim.o \
		glmimg_sdl.o \
		glmimg_png.o \
		glmimg_jpg.o \
		glmimg_devil.o \
		glm.o \
		glm_util.o \
		glmimg.o \
		waymanager.o \
		xmlruta.o \
		moc_uigc2.o \
		moc_GLWidget.o \
		qrc_imagenesRutas.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		EntornQTGC2.pro
QMAKE_TARGET  = EntornQTGC2
DESTDIR       = 
TARGET        = EntornQTGC2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_uigc2.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: EntornQTGC2.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtOpenGL.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile EntornQTGC2.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtOpenGL.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile EntornQTGC2.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/EntornQTGC21.0.0 || $(MKDIR) .tmp/EntornQTGC21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/EntornQTGC21.0.0/ && $(COPY_FILE) --parents uigc2.h Util.h Model.h GLWidget.h cameracontrol.h collisionmanager.h coldet/src/box.h coldet/src/coldet.h coldet/src/coldetimpl.h coldet/src/math3d.h coldet/src/mytritri.h coldet/src/sysdep.h lightmanager.h object.h objectmanager.h lights.h expat/xmltok_impl.h expat/xmltok.h expat/xmlrole.h expat/winconfig.h expat/utf8tab.h expat/nametab.h expat/macconfig.h expat/latin1tab.h expat/internal.h expat/iasciitab.h expat/expat_external.h expat/expat.h expat/asciitab.h expat/ascii.h expat/amigaconfig.h expat/XMLParser.h xmlmanager.h glwidgetmap.h pointer.h glm/glmint.h glm/glm.h waymanager.h xmlruta.h .tmp/EntornQTGC21.0.0/ && $(COPY_FILE) --parents imagenesRutas.qrc .tmp/EntornQTGC21.0.0/ && $(COPY_FILE) --parents main.cpp uigc2.cpp Model.cpp GLWidget.cpp cameracontrol.cpp collisionmanager.cpp coldet/src/box.cpp coldet/src/box_bld.cpp coldet/src/coldet.cpp coldet/src/coldet_bld.cpp coldet/src/math3d.cpp coldet/src/mytritri.cpp coldet/src/sysdep.cpp coldet/src/tritri.c lightmanager.cpp object.cpp objectmanager.cpp lights.cpp expat/xmltok.c expat/xmlrole.c expat/xmlparse.c expat/XMLParser.cpp xmlmanager.cpp glwidgetmap.cpp pointer.cpp glm/glmimg_sim.c glm/glmimg_sdl.c glm/glmimg_png.c glm/glmimg_jpg.c glm/glmimg_devil.c glm/glm.cpp glm/glm_util.cpp glm/glmimg.cpp waymanager.cpp xmlruta.cpp .tmp/EntornQTGC21.0.0/ && $(COPY_FILE) --parents uigc2.ui .tmp/EntornQTGC21.0.0/ && (cd `dirname .tmp/EntornQTGC21.0.0` && $(TAR) EntornQTGC21.0.0.tar EntornQTGC21.0.0 && $(COMPRESS) EntornQTGC21.0.0.tar) && $(MOVE) `dirname .tmp/EntornQTGC21.0.0`/EntornQTGC21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/EntornQTGC21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_uigc2.cpp moc_GLWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_uigc2.cpp moc_GLWidget.cpp
moc_uigc2.cpp: uigc2.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) uigc2.h -o moc_uigc2.cpp

moc_GLWidget.cpp: Model.h \
		Util.h \
		cameracontrol.h \
		lightmanager.h \
		lights.h \
		objectmanager.h \
		object.h \
		glm/glm.h \
		xmlmanager.h \
		expat/XMLParser.h \
		glwidgetmap.h \
		collisionmanager.h \
		coldet/src/coldet.h \
		pointer.h \
		GLWidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) GLWidget.h -o moc_GLWidget.cpp

compiler_rcc_make_all: qrc_imagenesRutas.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_imagenesRutas.cpp
qrc_imagenesRutas.cpp: imagenesRutas.qrc \
		images/controls.png \
		images/menu.png \
		images/smile.png
	/usr/bin/rcc -name imagenesRutas imagenesRutas.qrc -o qrc_imagenesRutas.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_uigc2.h
compiler_uic_clean:
	-$(DEL_FILE) ui_uigc2.h
ui_uigc2.h: uigc2.ui \
		GLWidget.h \
		glwidgetmap.h \
		Model.h \
		Util.h \
		cameracontrol.h \
		lightmanager.h \
		lights.h \
		objectmanager.h \
		object.h \
		glm/glm.h \
		xmlmanager.h \
		expat/XMLParser.h \
		glwidgetmap.h \
		collisionmanager.h \
		coldet/src/coldet.h \
		pointer.h \
		Model.h \
		Util.h \
		cameracontrol.h \
		collisionmanager.h \
		coldet/src/coldet.h
	/usr/bin/uic-qt4 uigc2.ui -o ui_uigc2.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp uigc2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

uigc2.o: uigc2.cpp uigc2.h \
		ui_uigc2.h \
		GLWidget.h \
		Model.h \
		Util.h \
		cameracontrol.h \
		lightmanager.h \
		lights.h \
		objectmanager.h \
		object.h \
		glm/glm.h \
		xmlmanager.h \
		expat/XMLParser.h \
		glwidgetmap.h \
		collisionmanager.h \
		coldet/src/coldet.h \
		pointer.h \
		xmlruta.h \
		waymanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uigc2.o uigc2.cpp

Model.o: Model.cpp Model.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Model.o Model.cpp

GLWidget.o: GLWidget.cpp GLWidget.h \
		Model.h \
		Util.h \
		cameracontrol.h \
		lightmanager.h \
		lights.h \
		objectmanager.h \
		object.h \
		glm/glm.h \
		xmlmanager.h \
		expat/XMLParser.h \
		glwidgetmap.h \
		collisionmanager.h \
		coldet/src/coldet.h \
		pointer.h \
		waymanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLWidget.o GLWidget.cpp

cameracontrol.o: cameracontrol.cpp cameracontrol.h \
		collisionmanager.h \
		coldet/src/coldet.h \
		waymanager.h \
		xmlruta.h \
		expat/XMLParser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cameracontrol.o cameracontrol.cpp

collisionmanager.o: collisionmanager.cpp collisionmanager.h \
		coldet/src/coldet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o collisionmanager.o collisionmanager.cpp

box.o: coldet/src/box.cpp coldet/src/sysdep.h \
		coldet/src/box.h \
		coldet/src/math3d.h \
		coldet/src/mytritri.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o box.o coldet/src/box.cpp

box_bld.o: coldet/src/box_bld.cpp coldet/src/sysdep.h \
		coldet/src/box.h \
		coldet/src/math3d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o box_bld.o coldet/src/box_bld.cpp

coldet.o: coldet/src/coldet.cpp coldet/src/sysdep.h \
		coldet/src/coldetimpl.h \
		coldet/src/coldet.h \
		coldet/src/box.h \
		coldet/src/math3d.h \
		coldet/src/mytritri.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o coldet.o coldet/src/coldet.cpp

coldet_bld.o: coldet/src/coldet_bld.cpp coldet/src/sysdep.h \
		coldet/src/coldetimpl.h \
		coldet/src/coldet.h \
		coldet/src/box.h \
		coldet/src/math3d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o coldet_bld.o coldet/src/coldet_bld.cpp

math3d.o: coldet/src/math3d.cpp coldet/src/sysdep.h \
		coldet/src/math3d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o math3d.o coldet/src/math3d.cpp

mytritri.o: coldet/src/mytritri.cpp coldet/src/sysdep.h \
		coldet/src/mytritri.h \
		coldet/src/box.h \
		coldet/src/math3d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mytritri.o coldet/src/mytritri.cpp

sysdep.o: coldet/src/sysdep.cpp coldet/src/sysdep.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sysdep.o coldet/src/sysdep.cpp

tritri.o: coldet/src/tritri.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o tritri.o coldet/src/tritri.c

lightmanager.o: lightmanager.cpp lightmanager.h \
		lights.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lightmanager.o lightmanager.cpp

object.o: object.cpp object.h \
		glm/glm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object.o object.cpp

objectmanager.o: objectmanager.cpp objectmanager.h \
		object.h \
		glm/glm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objectmanager.o objectmanager.cpp

lights.o: lights.cpp lights.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lights.o lights.cpp

xmltok.o: expat/xmltok.c expat/winconfig.h \
		expat/macconfig.h \
		expat/amigaconfig.h \
		expat/expat_external.h \
		expat/internal.h \
		expat/xmltok.h \
		expat/nametab.h \
		expat/xmltok_impl.h \
		expat/ascii.h \
		expat/xmltok_impl.c \
		expat/asciitab.h \
		expat/utf8tab.h \
		expat/iasciitab.h \
		expat/latin1tab.h \
		expat/xmltok_ns.c
	$(CC) -c $(CFLAGS) $(INCPATH) -o xmltok.o expat/xmltok.c

xmlrole.o: expat/xmlrole.c expat/winconfig.h \
		expat/macconfig.h \
		expat/amigaconfig.h \
		expat/expat_external.h \
		expat/internal.h \
		expat/xmlrole.h \
		expat/xmltok.h \
		expat/ascii.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o xmlrole.o expat/xmlrole.c

xmlparse.o: expat/xmlparse.c expat/winconfig.h \
		expat/macconfig.h \
		expat/amigaconfig.h \
		expat/ascii.h \
		expat/expat.h \
		expat/expat_external.h \
		expat/internal.h \
		expat/xmltok.h \
		expat/xmlrole.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o xmlparse.o expat/xmlparse.c

XMLParser.o: expat/XMLParser.cpp expat/XMLParser.h \
		expat/expat.h \
		expat/expat_external.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o XMLParser.o expat/XMLParser.cpp

xmlmanager.o: xmlmanager.cpp xmlmanager.h \
		expat/XMLParser.h \
		objectmanager.h \
		object.h \
		glm/glm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xmlmanager.o xmlmanager.cpp

glwidgetmap.o: glwidgetmap.cpp glwidgetmap.h \
		Model.h \
		Util.h \
		cameracontrol.h \
		collisionmanager.h \
		coldet/src/coldet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidgetmap.o glwidgetmap.cpp

pointer.o: pointer.cpp pointer.h \
		objectmanager.h \
		object.h \
		glm/glm.h \
		cameracontrol.h \
		collisionmanager.h \
		coldet/src/coldet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pointer.o pointer.cpp

glmimg_sim.o: glm/glmimg_sim.c glm/glm.h \
		glm/glmint.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o glmimg_sim.o glm/glmimg_sim.c

glmimg_sdl.o: glm/glmimg_sdl.c glm/glm.h \
		glm/glmint.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o glmimg_sdl.o glm/glmimg_sdl.c

glmimg_png.o: glm/glmimg_png.c glm/glm.h \
		glm/glmint.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o glmimg_png.o glm/glmimg_png.c

glmimg_jpg.o: glm/glmimg_jpg.c glm/glm.h \
		glm/glmint.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o glmimg_jpg.o glm/glmimg_jpg.c

glmimg_devil.o: glm/glmimg_devil.c glm/glm.h \
		glm/glmint.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o glmimg_devil.o glm/glmimg_devil.c

glm.o: glm/glm.cpp glm/glm.h \
		glm/glmint.h \
		collisionmanager.h \
		coldet/src/coldet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glm.o glm/glm.cpp

glm_util.o: glm/glm_util.cpp glm/glm.h \
		glm/glmint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glm_util.o glm/glm_util.cpp

glmimg.o: glm/glmimg.cpp glm/glm.h \
		glm/glmint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glmimg.o glm/glmimg.cpp

waymanager.o: waymanager.cpp waymanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o waymanager.o waymanager.cpp

xmlruta.o: xmlruta.cpp xmlruta.h \
		expat/XMLParser.h \
		waymanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xmlruta.o xmlruta.cpp

moc_uigc2.o: moc_uigc2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_uigc2.o moc_uigc2.cpp

moc_GLWidget.o: moc_GLWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GLWidget.o moc_GLWidget.cpp

qrc_imagenesRutas.o: qrc_imagenesRutas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_imagenesRutas.o qrc_imagenesRutas.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

